version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - run: npm install
      - run: npm run lint:ci
      - run: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
