version: 2
jobs:
  install:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - run: npm install
      - run: npm run lint:ci
      - run: npm run test
  build-image:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - run: docker build -t campvanilla/crudtest.com:latest .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-image:
          requires:
            - test
          filters:
            branches:
              only: master
