version: 2

jobs:
  install:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - run: npm install
      - run: npm run lint:ci
      - run: npm run test
  build-image-and-push:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            chmod +x /tmp/docker/*
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: Build Image and Deploy to DockerHub
          command: |
            docker build -t campvanilla/crudtest-api:latest .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push campvanilla/crudtest-api:latest


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build-image-and-push:
          requires:
            - test
          filters:
            branches:
              only: master
